name: Installs Component by uid and version

inputs:
  uid:
    description: Component uid
    required: true
  
  version:
    description: Component version
    required: true

  use-mmc-cache:
    description: Use local MMC cache
    required: false
    default: 'false'

  server-wrapper-profile:
    description: Use server wrapper profile
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:  
    - name: Install Component
      shell: pwsh
      working-directory: component
      run: |
        ../installComponent.ps1 "${{ inputs.uid }}" "${{ inputs.version }}" -MMCPatch:$${{ inputs.use-mmc-cache }} -ServerWrapperProfile:$${{ inputs.server-wrapper-profile }}

    - name: Get latest Fabric Loader version
      if: ${{ inputs.uid == 'net.fabricmc.intermediary' }}
      id: fabric-loader
      shell: pwsh
      run: |
        "version=$(./componentsIndex.ps1 'net.fabricmc.fabric-loader')" >> $env:GITHUB_OUTPUT

    - name: Install Fabric Loader
      if: ${{ inputs.uid == 'net.fabricmc.intermediary' }}
      shell: pwsh
      working-directory: component
      run: |
        ../installComponent.ps1 "net.fabricmc.fabric-loader" "${{ steps.fabric-loader.outputs.version }}"